@startuml

left to right direction
skinparam packageStyle rectangle

' Роли
:Тренер: as couch
:Авторизованный пользователь: as user <<Клиент>>
:Неавторизованный пользователь: as un_user
:Приложение: as app <<Следим за питанием>>
:База данных: as database <<Продукты>>

couch -->  user 

usecase uc_reg  as "Зарегистрироваться
в приложении"
usecase uc_edit_profile  as "Редактировать профиль"
usecase  uc_sign_in as "Авторизоваться в приложении"

usecase show_callories as "Отобразить каллории
из расчёта
массы продукта"

usecase view_stat as "Посмотреть статистистику"
usecase view_average as "Посмотреть среднее
за месяц"

usecase enter_data  as "Внести данные
измерений"
usecase add_mass as "Внести масссу"
usecase add_dateas "Ввести дату"

' Рецепты могут создать и пользователи и клиенты
usecase create_recipe  as "Создать рецепт"
usecase uc_check_eat as "Выбрать продукт в БД"

usecase uc_add_eat  as "Внести массу продукта"

usecase choose_recipe as "Выбрать рецепт из меню
тренера"
usecase save_recipe as "Добавить рецепт
в дневной рацион"
usecase edit_recipe  as "Редактировать рецепт"

usecase view_recipe as "Посмотреть рецепт"

usecase configure_filters as "Настроить фильтры"


usecase view_history_schedule  as "Посмотреть историю
и график"
usecase select_period as "Выбрать период:
день/неделя/месяц/год"
usecase select_kitchen as "Выбрать уровень
сложности приготовления"
usecase view_diet as "Посмотреть рацион клиента"

' Связи

un_user --> uc_reg
uc_reg <.. uc_edit_profile : extend
user --> uc_sign_in
uc_sign_in <.. uc_edit_profile : extend

user --> enter_data
enter_data <.. add_mass : include
enter_data <.. add_date : include

user --> create_recipe
create_recipe <.. uc_check_eat : include
create_recipe <.. uc_add_eat : include

user --> choose_recipe
user --> edit_recipe
choose_recipe <.. view_recipe : extend
choose_recipe <.. save_recipe : extend

user --> view_stat
view_stat <.. view_average : extend
view_stat <.. view_history_schedule : extend
view_stat <.. configure_filters : extend
configure_filters <.. select_period : extend
configure_filters <.. select_kitchen :extend


app --> show_callories
uc_check_eat <.. database : includes
uc_check_eat <.. show_callories : includes

couch --> view_diet
@enduml