@startuml

left to right direction

' Роли
:Тренер: as couch
:Пользователь: as user <<Клиент>>
:Приложение: as app

usecase (Зарегистрироваться в приложении)
usecase (Создать рецепт)
usecase (Найти продукт в БД)
usecase (Посмотреть статистистику)
usecase (Посмотреть график)
usecase (Посмотреть среднее за месяц)
usecase (Внести данные измерений)
usecase (Внести масссу)


@enduml